# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Personal Demographics Service (PDS) API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Personal Demographics Service (FHIR) API
  description: |
    ## Overview
    Use this API to access the [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/demographics) - the national electronic database of NHS patient details such as name, address, date of birth and NHS Number.

    You can:
    * search for patients
    * get patient details
    * update patient details

    You cannot currently use this API to:
    * check that you have the right NHS Number for a patient
    * create a new record for a birth
    * receive birth notifications
    * create a record for a new patient
    * register a new patient at a GP Practice - instead, use [National Health Application and Infrastructure Services (NHAIS)](https://digital.nhs.uk/services/nhais/nhais-developer-document-library)

    You can access the following data:
    * NHS Number
    * name
    * gender
    * addresses and contact details
    * birth information
    * death information
    * registered GP
    * nominated pharmacy (other related pharmacies coming soon)
    * consent information (coming soon)
    * related people (coming soon)

    Currently, this API can only be accessed by healthcare professionals, authenticated with an NHS smartcard or equivalent.
    Unauthenticated access and citizen access are on the roadmap.

    ## Related APIs
    The following APIs also give access to the Personal Demographics Service:
    - [Personal Demographics Service (SMSP) API](#) - use this if you want to get PDS data without an authenticated end used (no smartcard required). It is, however, read-only and searches are limited to a single result.
    - [Personal Demographics Service (HL7 V3) API](#) - use this if you want to use functions that are not yet available on the FHIR API.

    Once our roadmap is complete, the above APIs will become redundant.

    The following APIs are also related to this API:
    - [Organisation Data Service FHIR API](https://developer.nhs.uk/apis/ods/) - use this to get full details for the organisations related to the patient, such as their registered GP or nominated pharmacy.

    ## API status and roadmap
    This API is in [alpha](/reference-guide#api-status) - expect significant breaking changes.

    It is currently only available for sandbox testing, not for integration testing or production use.

    The following items are on our roadmap, in rough priority order:
    - addition of data fields for consent information, related people and more information on nominated pharmacies
    - integration testing service (target date: end of February 2020)
    - assurance process
    - production service - beta - search for patient and retrieve patient details (target date: end of March 2020)
    - production service - beta - update patient (target date: end of April 2020)
    - unauthenticated access - without NHS smartcard - similar to the PDS SMSP API (target date to be confirmed)
    - access for citizens using NHS Login (target date to be confirmed)
    - exit beta (target date: end of September 2020, subject to availability of beta testers)

    We are extremely keen to receive feedback on the API during alpha and beta,
    for example if there are data fields missing that you think you need.
    Please [get in touch](/help-and-support) with any comments or suggestions.

    ## Technology
    This API is [RESTful](/introduction-to-apis#basic-rest).

    It also conforms to the [FHIR](/introduction-to-apis#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You donâ€™t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    This API is available on the Internet, although access using NHS smartcards (see below)
    currently requires a connection to the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    ## Authorisation
    This API is [user-restricted](/security-and-authorisation#user-restricted-apis),
    meaning an end user must be present and authenticated to use it.

    The end user must be:
    - a healthcare professional
    - strongly authenticated, using either an NHS smartcard or a modern alternative

    The API uses Open ID Connect to authenticate the end user and OAuth 2.0 to authorise the calling system.
    It supports the following security patterns:
    * [user-restricted RESTful API - using NHS Identity - combined authentication and authorisation](/security-and-authorisation#user-restricted-restful-api-using-nhs-identity-combined-authentication-and-authorisation)
    * [user-restricted RESTful API - using NHS Identity - separate authentication and authorisation](/security-and-authorisation#user-restricted-restful-api-using-nhs-identity-separate-authentication-and-authorisation)

    In due course we plan to add the following:
    - access for citizens, using NHS Login
    - unattended access - without smartcard - similar to the PDS SMSP API

    ## Testing
    You can test this API in:
    * our [sandbox environment](/testing#sandbox-testing) for initial developer testing
    * our [integration test environment](/testing#integration-testing) for formal integration testing (coming soon)

    Our sandbox environment is a very basic simulation of the live service. It only covers a limited set of scenarios and is stateless, so does not actually persist any updates.

    For more details on sandbox testing, or to try out the sandbox using our "Try this API" feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:

    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)

    ## Assurance
    We are hoping to make the assurance process as lightweight and as self-service as possible.

    More details to follow.

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    * `GET /Patient` - search for patient
    * `GET /Patient/{id}` - get patient's personal details
    * `PATCH /Patient/{id}` - update patient's personal details
  contact:
    name: Personal Demographics Service FHIR API Support
    url: 'https://tbc.api.nhs.net'
    email: tbc-api-support@nhs.net
servers:
  - url: 'https://emea-demo8-test.apigee.net/personal-demographics'
    description: Sandbox service.
tags:
  - name: patients
paths:
  /Patient:
    parameters:
      - $ref: '#/components/parameters/RoleId'
    get:
      summary: Search for patient
      operationId: search-patient
      externalDocs:
        description: ODS codes and documentation.
        url: https://digital.nhs.uk/services/organisation-data-service
      description: |
        ## Overview
        Use this endpoint to search for a patient in PDS.

        You can search using a combination of:
          * given name
          * family name
          * gender
          * postcode
          * date of birth (range)
          * date of death (range)
          * registered GP practice

        ## Matching rules
        Search parameters are not case sensitive.

        Spaces in postcodes must match exactly, for example `AA11 1AA` will not match `AA111AA`.

        For date of birth and date of death, you can search for an exact date or for a range of dates.

        You can use wildcards in given name and family name. Wildcards must start with at least two characters; for example `Br\*` is valid, but `\*cDougal` is not. Multiple wildcards are allowed; for example `Br\*w\*` will match `Brown` and `Brower`.

        You can request a fuzzy search using the `_fuzzy-match` queryparameter. This will additionally:
          * match common homophones, such as `Smith` and `Smythe`, using the [Soundex](https://en.wikipedia.org/wiki/Soundex) algorithm
          * check for transposed names, such as `Adam Thomas` and `Thomas Adam`

        ## Search parameter options
        For a non-fuzzy search, the minimum set of search parameters is:
        * family name - but it can include wildcards
        * gender
        * date of birth - but it can be a range

        For a fuzzy search, use one of the following search parameter combinations:
        * given name, family name and date of birth
        * family name, date of birth, gender and postcode
        * given name date of birth, gender and postcode

        Do not use the date of death or registered GP Practice query paramaters for a fuzzy search; they will be ignored.

        If you use an invalid combination of query parameters, you will get an `INVALID_COMBINATION` error.

        ## Historic data search
        By default the endpoint only searches current information. You can search historic information, such as previous names or addresses using the `_history` query parameter.

        ## Scoring
        Every matched patient in the results list includes a score to indicate how closely the patient matched the search parameters.

        A score of 1.0 indicates an exact match. A score of less than 1.0 indicates a partial match.

        The result list is sorted in descending score order - best match first.

        Use the `_exact-match` query parameter to return exact matches only - where the score = 1.0.

        ## Number of results returned
        By default, the endpoint will return a maximum of 50 results.

        If there are more than 50 matching patients, the endpoint will return no results and the error response `TOO_MANY_MATCHES`. You can choose to limit the number of results returned using the `_max-results` query parameter.
        You can request a single, exact match using `_exact-match=true` and `_max-results=1`.

        ## Clinical safety and privacy
        This endpoint can return multiple matching patients for a given search, including partial matches.

        You should ensure that you design, build and test your software to minimise these risks:
        * an end user selects the wrong patient from the results presented, so there is a risk of clinical harm; for example due to retrieval of the wrong medical data
        * the end user has access to patientsâ€™ personal data, so there is a risk to patient privacy

        ## Sandbox testing
        You can test the following scenarios in our [sandbox environment](/testing#sandbox-testing):

        | Scenario                       | Request                                                      | Response                                   |
        | ------------------------------ | ------------------------------------------------------------ | ------------------------------------------ |
        | Successful simple search       | `family`=`Smith`, `gender`=`female`, `birthdate`=`eq2010-10-22` | HTTP Status 200 with single search result. |
        | Successful advanced search       | `family`=`Sm*`, `gender`=`female`, `birthdate`=`eq2010-10-22` | HTTP Status 200 with search result of two. |
        | Successful advanced search with `_max-results` parameter set.      | `family`=`Sm*`, `gender`=`female`, `birthdate`=`eq2010-10-22`, `_max-results`=`2` | HTTP Status 200 with search result of two. |
        | Successful advanced search with daterange parameters provided      | `family`=`Smith`, `gender`=`female`, `birthdate`=`ge2010-10-21`, `birthdate`=`le2010-10-23` | HTTP Status 200 with single search result. |
        | Successful algorithmic search      | `family`=`Smith`, `given`=`Jane` `gender`=`female`, `birthdate`=`eq2010-10-22`, `_fuzzy-match`=`true` | HTTP Status 200 with single search result. |
        | Unsuccessful search            | Any other valid search query parameters                      | HTTP Status 200 with no search results     |
        | Invalid date format            | `birthdate` or `death-date` query parameters with values not in format `YYYY-MM-DD` | HTTP Status 400 with problem description   |
        | Too few search parameters      | Any invalid combination of query parameters                  | HTTP Status 400 with problem description   |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:
        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)
      tags:
        - patients
      parameters:
        - name: _exact-match
          description: The search only returns results where the `score` field is 1.0.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _history
          description: The search looks for matches in historic information such as previous names and addresses.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _fuzzy-match
          description: A fuzzy search is performed, including checks for homophones and transposed names.
          example: true
          in: query
          required: false
          schema:
            type: boolean
            default: false
        - name: _max-results
          description: The maximum number of results to return between 1 and 50. The default is 50.
          example: 1
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 50
        - name: family
          description: "The patient's family name (surname)."
          examples:
            simple:
              value: Smith
              summary: Will also match Smythe if `_fuzzy-match` is specified.
            wildcarded:
              value: "Sm\\*t\\*"
              summary: 'Wildcards must contain at least two characters, this will match Smith, Smythe'
          in: query
          required: false
          schema:
            type: string
        - name: given
          description: "The patient's given name."
          example: Jane
          in: query
          required: false
          schema:
            type: string
        - name: gender
          description: Gender with which the patient identifies.
          example: female
          in: query
          required: false
          schema:
            $ref: components/schemas/Gender.yaml
        - name: birthdate
          in: query
          description: Date of birth in the format `<eq|ge|le>yyyy-mm-dd`. To specify a range, use `birthdate=geyyyy-mm-dd&birthdate=leyyyy-mm-dd`.
          examples:
            simple:
              value: eq2010-10-22
              description: Exact match date
            rangege:
              value: 'ge2010-10-22'
              description: Greater than or equals match, which matches 2010-10-22 or 2010-10-23
            rangele:
              value: 'le2010-10-22'
              description: Less than or equals match, which matches 2010-10-22 or 2010-10-21
          required: false
          schema:
            type: array
            items: 
              type: string
        - name: death-date
          in: query
          description: Date of death in the format `<eq|ge|le>yyyy-mm-dd`. To specify a range, use `death-date=geyyyy-mm-dd&death-date=leyyyy-mm-dd`.
          examples:
            simple:
              value: eq2010-10-22
              description: Exact match date
            rangege:
              value: ge2010-10-22
              description: Greater than or equals match which matches 2010-10-22 or 2010-10-23
            rangele:
              value: 'le2010-10-22'
              description: Less than or equals match, which matches 2010-10-22 or 2010-10-21
          required: false
          schema:
            type: string
            format: date
        - name: address-postcode
          description: The postcode of any of the patientâ€™s known addresses. White spaces in postcodes are significant; that is, LS16AE will not match LS1 6AE.
          examples:
            simple:
              value: LS1 6AE
              summary: 'Spaces important, will not match LS16AE'
            wildcarded:
              value: "LS1\\*"
              summary: "Will match LS16AE and 'LS1 6AE', 'LS1 6AB'"
          in: query
          required: false
          schema:
            type: string
        - name: general-practitioner
          description: "The Organisation Data Service (ODS) code of the patient's registered GP practice."
          example: Y00001
          in: query
          required: false
          schema:
            type: string
            format: ods_code
      responses:
        '200':
          description: 'A completed search, containing zero, one, or many matching patients.'
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    description: FHIR Resource Type.
                    default: Bundle
                  type:
                    type: string
                    description: FHIR Bundle Type.
                    default: searchset
                  timestamp:
                    type: string
                    description: Time the search was performed.
                    format: datetime
                    example: '2019-12-25T12:00:00+00:00'
                  total:
                    type: integer
                    description: Number of resources returned in search.
                    example: 1
                  entry:
                    type: array
                    description: |
                      A list of matched patients. Empty if none found. The patients are ordered by match score, best first. A maximum of 50 patients will be returned.
                    items:
                      type: object
                      properties:
                        fullUrl:
                          type: string
                          description: Absolute URL of the resource described in this item.
                          example: 'https://beta.api.digital.nhs.uk/Patient/9000000009'
                        search:
                          type: object
                          properties:
                            score:
                              description: Search score from 0.0 to 1.0.
                              type: number
                              minimum: 0.0
                              maximum: 1.0
                              example: 0.75
                        resource:
                          $ref: 'components/schemas/Patient.yaml'
              example:
                resourceType: Bundle
                type: searchset
                timestamp: '2019-12-25T12:00:00+00:00'
                total: 1
                entry:
                  - fullUrl: 'https://beta.api.digital.nhs.uk/Patient/9000000009'
                    search:
                      score: 1
                    resource:
                      $ref: components/examples/Patient.json
        '400':
          description: Invalid search paramaters supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                not-enough:
                  summary: too few search params
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: NO_SEARCHES_PERFORMED
                              display: Not enough search parameters were provided to be able to make a search.
                bad-combination:
                  summary: Invalid combination of search parameters
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_COMBINATION
                              display: Invalid combination for fields
  '/Patient/{id}':
    parameters:
      - $ref: '#/components/parameters/Id'
      - $ref: '#/components/parameters/RoleId'
    get:
      description: |
        ## Overview
        Returns personal details for the patient with the given NHS Number.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment:

        | Scenario              | Request                                         | Response                                      |
        | --------------------- | ----------------------------------------------- | --------------------------------------------- |
        | Patient exists        | `nhs_number`=`9000000009`                       | HTTP Status 200 with patient data in response |
        | Patient doesn't exist | `nhs_number`=`9111231130` (or any other valid NHS Number)  | HTTP Status 404 with problem description      |
        | Invalid NHS Number    | `nhs_number`=`9000000000` (or any invalid NHS Number)| HTTP Status 400 with problem description      |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)
      summary: "Retrieve a patient's record"
      operationId: get-patient
      tags:
        - patients
      responses:
        '200':
          description: Information successfully returned.
          headers:
            ETag:
              $ref: components/schemas/ETag.yaml
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/Patient.yaml
              example:
                $ref: components/examples/Patient.json
        '400':
          description: Invalid NHS number supplied.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: invalidNHSNumber
                          display: NHS Number 9000000000 is not a valid NHS number.
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: patientNotFound
                          display: Patient with NHS number 9111231130 could not be found.
    patch:
      description: |
        ## Overview
        Updates specific patient information.

        This is a 'patch' operation, meaning you can update specific parts of the patient record (such as a name or an address), as opposed to having to update the entire record.

        ## Patient record versioning
        To update a patient's record you must have retrieved it first.
        When you retrieve a patient record, you get a version number for the record (in the `ETag` header and in the `versionId` field in the response).
        You must then pass the record's version number in the update request (in the `If-Match` header).
        The update will only succeed if the patient record has not been updated in our database in the meantime.
        If the update succeeds, you will receive a copy of the update record in the response, including the new record version number.
        If you have a subsequent update you must use the new version number.

        ## Sandbox test scenarios
        You can test the following scenarios in our sandbox environment.
        Note that your changes will not be persisted.
        JSON Patch operations themselves are validated, but the resulting resource is not validated for correctness.

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        | Successful update                   | `nhs_number`=`9000000009`<br />Body: One of the provided examples<br />Headers: `If-Match`=`W/"2"`, `Content-Type`=`application/json-patch+json` | HTTP Status 200 with updated patient in response (but note that the update won't be persisted) |
        | Patient doesn't exist               | `nhs_number`=`9111231130` (or any other valid NHS Number)    | HTTP Status 404 with problem description         |
        | Invalid NHS Number                  | `nhs_number`=`9000000000` (or any invalid NHS Number)        | HTTP Status 400 with problem description         |
        | Missing resource version identifier | `If-Match` header missing or set to format other than `W/"<version>"` | HTTP Status 400 with problem description         |
        | Incorrect resource version          | `If-Match`=`W/"1"`                                           | HTTP Status 412 with problem description         |
        | Wrong content type                  | `Content-Type` header missing or other than `application/json-patch+json` | HTTP Status 415 with problem description         |
        | No patches sent                     | Send body with no `patches` attribute                        | HTTP Status 400 with problem description         |
        | Invalid patch operation(s)          | Send body with invalid JSON patches in `patches` attribute   | HTTP Status 400 with problem description         |

        You can try out the sandbox using the "Try this API" feature on the right hand side of this page.

        Alternatively, you can try out the sandbox using our Postman collection:

        [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/2871d49488699f3f5a67)


      summary: Update a patient's record
      operationId: update-patient-partial
      tags:
        - patients
      externalDocs:
        description: IETF RFC 6902, which defines json-patch.
        url: https://tools.ietf.org/html/rfc6902
      parameters:
        - $ref: '#/components/parameters/IfMatch'
      requestBody:
        required: true
        content:
          # application/json-patch+json: FIXME - should be set to this but we have had to change it due to an Apigee SmartDocs bug.
          # See email chain w subject "Try this API feature for PATCH/POST APIs" between Alex H, Tony H, and David Macdonald from Apigee
          application/json:
            schema:
              type: object
              required:
                - patches
              properties:
                correction:
                  description: Set to true if the update is correcting previously incorrect data.
                  type: boolean
                  default: false
                patches:
                  $ref: components/schemas/JsonPatch.yaml
            examples:
              add-name:
                summary: Add a new name to the patient
                value:
                  $ref: components/examples/requests/PatientPatch/add-name.json
              update-name:
                summary: Update the first given name entry
                value:
                  $ref: components/examples/requests/PatientPatch/update-name.json
              delete-name:
                summary: Remove a name no longer in use
                value:
                  $ref: components/examples/requests/PatientPatch/delete-name.json
      responses:
        '200':
          description: Patient updated.
          headers:
            ETag:
              $ref: components/schemas/ETag.yaml
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/Patient.yaml
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                missing-if-match:
                  summary: Missing If-Match header
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: versionNotSupplied
                              display: If-Match header must be supplied to update this resource.
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidNHSNumber
                              display: NHS Number 9000000000 is not a valid NHS number.
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted.
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidPatchOperation
                              display: 'Invalid patch: Cannot perform the operation at a path that does not exist.'
        '404':
          description: Patient not found.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: not-found
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: patientNotFound
                          display: Patient with NHS number 9111231130 could not be found.
        '412':
          $ref: '#/components/responses/412PreconditionFailed'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: unsupportedMediaType
                          display: "Must be 'application/json-patch+json'."
components:
  parameters:
    Id:
      name: id
      in: path
      description: "The patient's NHS Number."
      required: true
      schema:
        $ref: components/schemas/NhsNumber.yaml
    IfMatch:
      in: header
      name: If-Match
      description: |
        Latest known version identifier enclosed in quotes preceded by `W/`.

        Send the value of this resource's `ETag` response header (or `meta.versionId` property) as received.
      required: true
      schema:
        type: string
        format: "^W\\/\\\"[[:print:]]+\\\"$"  # Printable characters enclosed in quotes. See: https://tools.ietf.org/html/rfc7230#section-3.2.6
        example: 'W/"2"'
    RoleId:
      in: header
      name: NHSD-Session-URID
      description: |
        A User Role ID (URID), also known as a User Role Profile ID (URPID), specifies the role the user is acting in. This dictates the actions they can perform.

        A URID belongs to a user (they are not generic) and a user may have more than one.

        Note: This parameter is not required when interacting with the Sandbox.
      required: true
      schema:
        type: string
        format: '^[0-9]+$'
        example: '555021935107'
  schemas:
    Patient:
      $ref: components/schemas/Patient.yaml
    OperationOutcome:
      $ref: components/schemas/OperationOutcome.yaml
  responses:
    412PreconditionFailed:
      description: |
        Precondition failed.

        The version identifier submitted in the `If-Match` header was not the latest version of the resource.
      content:
        application/fhir+json:
          schema:
            $ref: components/schemas/OperationOutcome.yaml
          example:
            resourceType: OperationOutcome
            issue:
              - severity: error
                code: conflict
                details:
                  coding:
                    - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                      version: '1'
                      code: versionMismatch
                      display: This resource has changed since you last read. Please re-read and try again with the new version number.
